import type { Metadata } from "next";
import { Exo_2} from "next/font/google";
import "./globals.css";

const lato = Exo_2({
  weight: ["300", "700"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
